name: MirrorBot Environment

on:
  push:
    branches: [master]
    paths-ignore: [README.md]
  workflow_dispatch:

env:
  # Change these values if you have forked it for your own works
  GitHubMail: "75479460+tongueiok-1@users.noreply.github.com"
  GitHubName: "tongueiok-1"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Git
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - uses: rokibhasansagar/slimhub_actions@main

      - name: Compile Docker container
        run: |
          git clone --recursive https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.MIRROR_REPOSLUG }} source
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
          docker image ls

      - name: Run Docker container
        timeout-minutes: 340
        continue-on-error: true
        run: |
          docker run --privileged --rm -i mirror-bot

      - name: Initiate next instance
        continue-on-error: true
        run: |
          # ${GITHUB_REPOSITORY} is the repo slug which runs this script
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          echo $RANDOM > looper.txt
          git add looper.txt
          git commit -m "$(TZ='Asia/Kolkata' date +"%b%e, %l:%M %p")"
          git push -q https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:master
